apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg5
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: dGVzZmsyRzV6T2xnaElhajVvTHA=
---
apiVersion: v1
kind: Secret
metadata:
  name: vote-app-secrets
type: Opaque
data:
  SECRET_KEY: eW91LXdpbGwtbmV2ZXItZ3Vlc3M=
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: dGVzZmsyRzV6T2xnaElhajVvTHA=
